[tasks.generate]
script = [
    "curl https://api.e-boekhouden.nl/swagger/v1/swagger.json --create-dirs -o /tmp/eboekhouden.yaml",
    "sed -i.bak \"s/\\\"info\\\": {/\\\"servers\\\":[{\\\"url\\\": \\\"https:\\/\\/api.e-boekhouden.nl\\\"}],\\\"info\\\": {/\" /tmp/eboekhouden.yaml",
    "npx openapi-generator-cli generate -i /tmp/eboekhouden.yaml -o packages/eboekhouden -g rust --package-name eboekhouden --additional-properties=bestFitInt=true,library=reqwest-trait,supportMiddleware=true,topLevelApiClient=true,useBonBuilder=true,useSingleRequestParameter=true",
    "cargo run -p scripts --bin modify",
    "cargo clippy --fix --allow-dirty",
    "npx prettier --write .",
    "cargo fmt",
    "cargo sort --workspace",
]
workspace = false
